services:
  app:
    labels:
    - traefik.enable=true
    - traefik.docker.network=traefik

    - traefik.http.routers.auth-server.rule=Host(`${DOMAIN_NAME?}`)
    - traefik.http.routers.auth-server.entrypoints=http
    networks:
      - traefik
      - default

networks:
  traefik:
    external: true

  default:
